spring.r2dbc:
  # 不要改成 r2dbc:pool:mysql://127.0.0.1:33306/us, 否则initial-size会失去作用
  # https://stackoverflow.com/questions/65303082/how-to-enable-connection-pooling-with-spring-boot-starter-data-r2dbc
  url: r2dbc:mysql://127.0.0.1:33306/us?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456
  pool:
    # 可以不要
    enabled: true
    initial-size: 5
    max-size: 100
    max-idle-time: 30m
    validation-query: SELECT 1

event:
  loop:
    threads: 10

logging.level.org.springframework:
  transaction: TRACE
  data.r2dbc.connectionfactory: DEBUG